### PR TITLE
Allow usage with Ecto betas

### PR DESCRIPTION
**Pull request by crismali**

### CODE REVIEW

**Comment by seanabrahams** [comment]
@crismali Thanks for the PR! Do you happen to be using the `GraphQL.Relay.Connection.Ecto` module (https://github.com/graphql-elixir/graphql_relay/blob/master/lib/graphql/relay/connection/ecto.ex) with Ecto 2 beta and know it to be working? I haven't tested it against Ecto 2 yet and fear that they may not be compatible.

Hopefully it won't be too difficult to support both Ecto 1.x and 2.x with some pattern matching or a conditional if it turns out they're not compatible. Thanks!

**Comment by crismali** [comment]
Looks compatible, I haven't had any issues with it so far.

**Comment by crismali** [comment]
Any chance of the ecto dependency changing? Right now Ecto betas can't be used even when not using the ecto integration provided in this package.

**Comment by seanabrahams** [comment]
@crismali Thanks for pinging for this again. The most recent commit in this PR is a little too restrictive and removes `sqlite_ecto` which results in failing tests. I understand why you removed `sqlite_ecto` since it has a dependency on ecto `~> 1.0` with no support for Ecto 2.0 as of yet.

We originally discussed whether Ecto support should be included in this repo and decided to include it since it would be optional. However this is a good example for why separating it is desirable.

I'll look into removing the `sqlite_ecto` dependency and instead use `postgrex` for testing so we can get a proper `~> 1.1 or ~> 2.0` dependency for `ecto`. Alternatively, we can separate out Ecto support. I'll look into this now.

**Comment by seanabrahams** [comment]
@crismali After investigating what it would take to support both Ecto 1.x and 2.x in this package it's clear that Ecto support should be moved to another package.

I've created a new issue for this here https://github.com/graphql-elixir/graphql_relay/issues/22

Thanks for bringing this issue up!

cc @joshprice

**Comment by crismali** [comment]
A separate package sounds great, thanks!

**Comment by seanabrahams** [comment]
In the end it turned out it was easier to update this library instead. Grab v0.4!

**Pull request closed without merging**
